### ISSUE TITLE
Aesthetics upgrade - PrettyPlotlib compatibility

### ISSUE THREAD

**Issue by ict4eo** [HamsterHuey/easyplot#3]
I have **no**  idea if its possible, but it seems to me that it would be a great win if you could also offer support for the PrettyPlot (http://olgabot.github.io/prettyplotlib/) approach - then we have an ideal combination of plots that are both easy to make and are good looking!

**Comment by HamsterHuey** [comment]
Closing this as the prettyplotlib author is no longer supporting it and recommends seaborn instead. Source: https://github.com/olgabot/prettyplotlib

Interested users who still wish to use prettyplotlib with easyplot can grab Easyplot from this branch: https://github.com/HamsterHuey/easyplot/tree/prettyplotlib_compatibility

This will not be merged back into master.
