### ISSUE TITLE
add_plot with x axis as list of datetime objects

### ISSUE THREAD

**Issue by geeday** [HamsterHuey/easyplot#5]
If I use the add_plot method where the x axis is a list of datetime objects:

a get an error with line 143:

ax.ticklabel_format(useOffset=False)

  File "C:\Python27\lib\site-packages\easyplot\easyplot.py", line 143, in add_plot
    ax.ticklabel_format(useOffset=False) # Prevent offset notation in plots
  File "C:\Python27\lib\site-packages\matplotlib\axes\_base.py", line 2275, in ticklabel_format
    "This method only works with the ScalarFormatter.")
AttributeError: This method only works with the ScalarFormatter.

the first time I plot a line by creating a new instance, the chart is fine, the line in question only appers in add_plot.

if I comment this line out, I get what I want.

Kind regards

**Comment by HamsterHuey** [comment]
Hi there, would it be possible for you to share a code snippet that I can try locally to reproduce the issue? Thanks!

**Comment by HamsterHuey** [comment]
Ah, okay, I think I understand. You're saying that if you comment out line 143 
`ax.ticklabel_format(useOffset=False)`
then you don't have the issue with `add_plot`?
Could you share a code example all the same where the new instance plots fine but the add_plot command fails?

**Comment by geeday** [comment]
Hi,
The code below is based upon your example.

adding the second line causes the error. if you only plot one line everything is fine.

G.



#python

import matplotlib.pyplot as plt
from easyplot import EasyPlot
import datetime
base = datetime.datetime.today()
x = [base - datetime.timedelta(days=x) for x in range(0, 5)]
eplot = EasyPlot(x, [1,2,3,4,5], 'b-o', label='y = x**2', showlegend=True,
                 xlabel='x', ylabel='y', title='title', grid='on')
eplot.add_plot(x, [4,5,6,7,8], 'r--s', label='y = x**3')
plt.show()

**Comment by HamsterHuey** [comment]
Thanks a lot. I was able to reproduce it and I'm pretty sure I know how to fix it without having to give up on disabling the offset plotting feature in matplotlib. It's probably going to take me longer to brush up on uploading packages on PyPi than it is to fix this bug :-/. I'll post an update once I have this fixed and would appreciate if you could test it out and let me know if it works.

**Comment by HamsterHuey** [comment]
Hi there. Could you try using the update from this branch: https://github.com/HamsterHuey/easyplot/tree/Bugfix_-_Issue_%235

The issue should be fixed. Now, `useOffset` is only applied to the x or y-axis if the corresponding formatter is of type `ScalarFormatter`. Let me know if this fixes the issue for any tests/examples you try. If all is well, I'll merge this back into Master in a few days.

Thanks for the bug report and hope the library is proving useful!

**Comment by HamsterHuey** [comment]
@geeday I'd appreciate if you could provide an update if this resolved the issue for you. Otherwise, I'll probably push this out in a few days and close this bug at that point in time unless someone reports a similar issue further down the line.

**Comment by geeday** [comment]
I was able to simply overwrite the EasyPlot.py file and the issue seems to be fixed.
thanks

**Comment by HamsterHuey** [comment]
Thanks for the feedback. I'll push this fix out to PyPi soon
